### ISSUE TITLE
Clang linking error

### ISSUE THREAD

**Issue by achiefa** [MapCollaboration/NangaParbat#8]
Dear All,

I am trying to build NangaParbat with macOS Monterey 12.6. I have installed all the dependences with the exception of ROOT. 

The error I get during the compilation is:

`[ 75%] Linking CXX shared library libNangaParbat.dylib
ld: warning: directory not found for option '-Llib'
Undefined symbols for architecture x86_64:
  "LHAPDF::mkPDF(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      NangaParbat::FastInterface::FastInterface(YAML::Node const&) in fastinterface.cc.o
      NangaParbat::EmitTMDGrid(YAML::Node const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<double, std::__1::allocator<double> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, NangaParbat::ThreeDGrid const&) in createtmdgrid.cc.o
      NangaParbat::EmitStructGridDirect(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, NangaParbat::FourDGrid const&, int const&) in createstructgrid.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libNangaParbat.dylib] Error 1
make[1]: *** [src/CMakeFiles/NangaParbat.dir/all] Error 2
make: *** [all] Error 2
`

The compiler is AppleClang 14.0 provided by Apple's command line tools.

The problem seems to be related to the mkPDF function from the LHAPDF package. However, I checked the LHAPDF path within ccmake and the path is reported correctly.

I have also looked at the CMakeError.log, which reports two error messages:

`Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /Library/Developer/CommandLineTools/usr/bin/cc 
Build flags: 
Id flags:  
The output was:
1
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

`Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /Library/Developer/CommandLineTools/usr/bin/c++ 
Build flags: 
Id flags:  
The output was:
1
ld: library not found for -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Are these two errors connected with the former?

Best,

Amedeo

**Comment by vbertone** [comment]
Dear Amedeo,

thanks for inquiring.
I cannot see on the spot where the problem is.
However, since you will be developing the code, I have just sent you an invitation to the private development branch of NangaPargat (NangaParbat-Beta).
Before digging into this error, could you please try to compile that version of the code?
If this (or any other problem) shows up again we can investigate futher. Let me know.

Best,
Valerio

**Comment by achiefa** [comment]
Dear Valerio,

Thanks for your support. 
Unfortunately, I still get the same error:

`Undefined symbols for architecture x86_64:
  "LHAPDF::mkPDF(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      NangaParbat::FastInterface::FastInterface(YAML::Node const&) in fastinterface.cc.o
      NangaParbat::EmitTMDGrid(YAML::Node const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<double, std::__1::allocator<double> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, NangaParbat::ThreeDGrid const&) in createtmdgrid.cc.o
      NangaParbat::EmitStructGridDirect(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, NangaParbat::FourDGrid const&, int const&) in createstructgrid.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libNangaParbat.dylib] Error 1
make[1]: *** [src/CMakeFiles/NangaParbat.dir/all] Error 2
make: *** [all] Error 2`

I have also tried to compile with the Macports' compiler (GNU package), but now the error message is quite odd. 
I just report the first few lines of the error message (the other lines look similar):
 
`
Undefined symbols for architecture x86_64:
__ZN4YAML15ostream_wrapper5writeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE", referenced from:
      __ZN4YAML7Emitter15WriteStreamableIdEERS0_T_ in fastinterface.cc.o
      __ZN4YAML7Emitter17WriteIntegralTypeIiEERS0_T_.isra.0 in fastinterface.cc.o
      __ZNK11NangaParbat13FastInterface15ComputeTablesDYERKSt6vectorINS_11DataHandlerESaIS2_EE in fastinterface.cc.o
      __ZNK11NangaParbat13FastInterface18ComputeTablesSIDISERKSt6vectorINS_11DataHandlerESaIS2_EE in fastinterface.cc.o
      __ZN4YAML7Emitter15WriteStreamableIdEERS0_T_ in preprocessE288.cc.o
      __ZN11NangaParbat14PreprocessE288ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_RKb in preprocessE288.cc.o
      __ZN4YAML7Emitter15WriteStreamableIdEERS0_T_ in preprocessE605.cc.o
 .
 .
`

which eventually ends with:

`
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [src/libNangaParbat.dylib] Error 1
make[1]: *** [src/CMakeFiles/NangaParbat.dir/all] Error 2
make: *** [all] Error 2
`

Should I try a different setup/configuration?
